/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
	aws_project_region: "us-east-2",
	aws_cognito_identity_pool_id:
		"us-east-2:3d76315c-c8eb-4c16-b039-a65440af7619",
	aws_cognito_region: "us-east-2",
	aws_user_pools_id: "us-east-2_f5Vs4Voia",
	aws_user_pools_web_client_id: "1mjp22tqadtmti5ts3cjg8t3de",
	oauth: {},
	aws_cognito_login_mechanisms: ["PREFERRED_USERNAME"],
	aws_cognito_signup_attributes: ["EMAIL"],
	aws_cognito_mfa_configuration: "OFF",
	aws_cognito_mfa_types: ["SMS"],
	aws_cognito_password_protection_settings: {
		passwordPolicyMinLength: 8,
		passwordPolicyCharacters: [],
	},
	aws_cognito_verification_mechanisms: ["EMAIL"],
	aws_appsync_graphqlEndpoint:
		"https://fgaji53ujbgj7dpvmyd2hmexau.appsync-api.us-east-2.amazonaws.com/graphql",
	aws_appsync_region: "us-east-2",
	aws_appsync_authenticationType: "API_KEY",
	aws_appsync_apiKey: "da2-h5emtm5bzffkbaphwti6idminm",
};

export default awsmobile;
